export const AUTH_START = "AUTH_START";
export const LOGGED_IN = "LOGGED_IN";
export const LOGGED_OUT = "LOGGED_OUT";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_CHECKED = "AUTH_CHECKED";

export const ORDER_CREATED = "ORDER_CREATED";
export const ORDER_CREATION_FAILED = "ORDER_CREATION_FAILED";
export const ORDER_UPDATED = "ORDER_UPDATED";
export const ORDER_UPDATE_FAILED = "ORDER_UPDATE_FAILED";
export const ORDER_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS";

export const USER_RETRIEVED = "USER_RETRIEVED";
export const USER_RETRIEVE_FAILED = "USER_RETRIEVE_FAILED";
export const RETRIEVING_USER_DATA = "RETRIEVING_USER_DATA";
